import {test,expect} from '@playwright/test'

test('create compare and restore versions without deleting newer snapshots',async({page,request})=>{
  const p=await (await request.get('/api/profile')).json()
  const r=await (await request.post('/api/resumes',{data:{name:`Versions ${Date.now()}`,selected_ids:p.items.map((i:{id:string})=>i.id)}})).json()
  await page.goto('/');await page.getByRole('button',{name:'Resumes',exact:true}).click();await page.getByRole('button',{name:`Open ${r.name}`,exact:true}).click()
  await page.getByRole('button',{name:'Versions',exact:true}).click()
  await page.getByRole('textbox',{name:'Version note',exact:true}).fill('Original story')
  await page.getByRole('button',{name:'Create version',exact:true}).click()
  await expect(page.getByRole('heading',{name:'v1',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Close drawer',exact:true}).click()
  await page.getByRole('button',{name:'02 Summary',exact:true}).click()
  await page.getByRole('textbox',{name:'Professional summary',exact:true}).fill('A shorter version of my experience.')
  await page.getByRole('button',{name:'Versions',exact:true}).click()
  await page.getByRole('textbox',{name:'Version note',exact:true}).fill('Shortened summary')
  await page.getByRole('button',{name:'Create version',exact:true}).click()
  await expect(page.getByRole('heading',{name:'v2',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Compare versions',exact:true}).click()
  await expect(page.locator('.diff-card')).toContainText('A shorter version of my experience.')
  await page.screenshot({path:'test-results/version-comparison.png',fullPage:true})
  await page.locator('.version-entry').filter({has:page.getByRole('heading',{name:'v1',exact:true})}).getByRole('button',{name:'Restore this version',exact:true}).click()
  await page.getByRole('button',{name:'Restore version',exact:true}).click()
  await expect(page.getByRole('heading',{name:'v3',exact:true})).toBeVisible()
  const restored=await (await request.get(`/api/resumes/${r.id}`)).json()
  expect(restored.document.personal.summary).toBe(r.document.personal.summary)
  expect((await (await request.get(`/api/resumes/${r.id}/versions`)).json()).length).toBe(3)
})
