import { test, expect } from './fixtures'
test('workspace theme backup and widget preferences persist', async ({ page, request }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Dark', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download complete workspace backup' }).click()
  expect((await downloaded).suggestedFilename()).toBe('CareerCanvas-backup.json')
  await page.getByRole('button', { name: 'Light', exact: true }).click()
  await page.getByRole('button', { name: 'Dashboard', exact: true }).click()
  await page.getByRole('button', { name: 'Customize dashboard' }).click()
  await page.getByRole('button', { name: 'Hide next', exact: true }).click()
  await page.getByRole('combobox', { name: 'Width of pipeline' }).selectOption('3')
  await page.getByRole('button', { name: 'Done customizing' }).click()
  await expect(page.getByText('One good step')).toHaveCount(0)
  await page.reload()
  await expect(page.getByText('One good step')).toHaveCount(0)
  await page.getByRole('button', { name: 'Customize dashboard' }).click()
  await page.getByRole('button', { name: 'Reset to default' }).click()
  await expect(page.getByRole('button', { name: 'Hide next', exact: true })).toBeVisible()
  const preferences = await (await request.get('/api/preferences')).json()
  expect(preferences.widgets.find((w: any) => w.id === 'next').visible).toBe(true)
})
