import { useEffect, useState } from 'react'
import { api, json } from './api'
import { Drawer } from './Profile'

export default function AISuggest({original,onAccept,onClose}:{original:string,onAccept:(text:string)=>void,onClose:()=>void}){
  const [status,setStatus]=useState<{enabled:boolean,external:boolean,provider:string,model:string}|null>(null),[consent,setConsent]=useState(false),[action,setAction]=useState('Improve Clarity'),[suggested,setSuggested]=useState(''),[flags,setFlags]=useState<{kind:string,value:string}[]>([]),[reviewed,setReviewed]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  useEffect(()=>{api<typeof status>('/ai/status').then(setStatus).catch(e=>setError(e.message))},[])
  return <Drawer title="Your words. Your approval." onClose={onClose}><div className="drawer-form"><p className="form-note">AI is optional. Suggestions never replace content automatically. Factual checks are conservative heuristics and can miss subtle changes; always review the full text.</p>{!status?.enabled?<p className="notice">AI is disabled. Configure AI_ENABLED, provider, and model in your local .env to enable it.</p>:<><label className="field"><span>Editing action</span><select value={action} onChange={e=>setAction(e.target.value)}>{['Make Shorter','Make Stronger','Improve Clarity','Make More Technical','Make More Concise'].map(a=><option key={a}>{a}</option>)}</select></label>{status.external&&<label className="selection-row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Send only the text below to Gemini for this suggestion. It will leave this device.</label>}<button className="button primary" disabled={busy||status.external&&!consent} onClick={async()=>{setBusy(true);try{const result=await api<{suggested:string,flags:typeof flags}>('/ai/suggest',json('POST',{original,action,consent_external:consent}));setSuggested(result.suggested);setFlags(result.flags);setReviewed(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?'Requesting…':'Request suggestion'}</button></>}<label className="field"><span>Original</span><textarea readOnly rows={5} value={original}/></label>{suggested&&<><label className="field"><span>Suggested · edit before accepting</span><textarea aria-label="Suggested text" rows={6} value={suggested} onChange={e=>{setSuggested(e.target.value);setReviewed(false)}}/></label>{flags.map((f,i)=><p className="error" key={i}>{f.kind}: new “{f.value}” — remove or correct unsupported details.</p>)}<button className="button secondary" onClick={()=>api<{flags:typeof flags}>('/ai/check',json('POST',{original,suggested})).then(r=>{setFlags(r.flags);setReviewed(true)})}>Check edited suggestion</button><div className="drawer-actions"><button className="button secondary" onClick={onClose}>Reject</button><button className="button primary" disabled={!reviewed||flags.length>0} onClick={()=>{onAccept(suggested);onClose()}}>Accept suggestion</button></div></>}{error&&<p className="error" role="alert">{error}</p>}</div></Drawer>
}
