import {useEffect,useState} from 'react'
import {ArrowUpRight,Plus,CalendarDays,Check,Leaf} from 'lucide-react'
import {api} from './api'
import {Profile} from './profile-types'
import {Resume} from './resume-types'
import {Job} from './Applications'
import {CareerRecord} from './Interviews'
import {AnalyticsData,Chart,Metric} from './Analytics'
import {goalProgress} from './Goals'
export default function Dashboard({navigate,onDemo}:{navigate:(page:string)=>void,onDemo:()=>void}){
 const [state,setState]=useState<{profile:Profile,resumes:Resume[],jobs:Job[],interviews:CareerRecord[],goals:CareerRecord[],analytics:AnalyticsData,activity:{id:string,action:string,created_at:string}[]}|null>(null),[error,setError]=useState('')
 useEffect(()=>{Promise.all([api<Profile>('/profile'),api<Resume[]>('/resumes'),api<Job[]>('/applications'),api<CareerRecord[]>('/career/interviews'),api<CareerRecord[]>('/career/goals'),api<AnalyticsData>('/analytics'),api<any[]>('/activity')]).then(([profile,resumes,jobs,interviews,goals,analytics,activity])=>setState({profile,resumes,jobs,interviews,goals,analytics,activity})).catch(e=>setError(e.message))},[])
 if(!state)return <p>{error||'Opening your career workspace…'}</p>
 const {profile,resumes,jobs,interviews,goals,analytics,activity}=state,upcoming=interviews.filter(i=>i.data.status==='Scheduled').sort((a,b)=>String(a.data.date).localeCompare(String(b.data.date))),followups=jobs.filter(j=>j.data.next_action).sort((a,b)=>a.data.deadline.localeCompare(b.data.deadline))
 return <>{!profile.items.length&&<section className="onboarding-banner"><div><span className="eyebrow">BUILD YOUR CAREER WORKSPACE</span><h2>Your experience deserves a clear story.</h2><p>Start with a resume, bring your career data, or explore a fully fictional demo.</p></div><div><button className="button primary" onClick={()=>navigate('Resumes')}>Create Resume</button><button className="button secondary" onClick={onDemo}>Load Demo Career</button><button className="text-action" onClick={()=>navigate('Settings')}>Import Career Data</button></div></section>}
 <div className="metrics-grid five"><Metric label="Active resumes" value={resumes.filter(r=>!r.archived).length} detail="A story for every opportunity"/><Metric label="Applications" value={jobs.length} detail={`${analytics.sent} applications sent`}/><Metric label="Interviews" value={upcoming.length} detail="Conversations ahead"/><Metric label="Offers" value={analytics.offers} detail="Recorded offers reached"/><Metric label="Profile complete" value={profile.completion.score+'%'} detail="Your reusable career foundation"/></div>
 <div className="dashboard-layout"><section className="dashboard-panel span-two"><div className="panel-heading"><h2>Your application pipeline</h2><button className="text-action" onClick={()=>navigate('Applications')}>View board <ArrowUpRight size={13}/></button></div><Chart data={analytics.pipeline.filter(p=>!['Rejected','Withdrawn','Technical Interview','Final Interview','Accepted'].includes(p.name))}/></section><section className="dashboard-panel next-move"><span className="eyebrow">YOUR NEXT MOVE</span><h2>One good step<br/>changes everything.</h2><p>{profile.completion.suggestions[0]||'Tailor your strongest resume to an opportunity you care about.'}</p><button className="button primary" onClick={()=>navigate('Resumes')}><Plus size={14}/>Open your resumes</button><Leaf className="next-move-leaf" size={100}/></section>
 <section className="dashboard-panel"><div className="panel-heading"><h2>Upcoming interviews</h2><CalendarDays size={16}/></div>{upcoming.slice(0,3).map(i=><button className="dashboard-row" onClick={()=>navigate('Interviews')} key={i.id}><span className="date-block">{i.data.date?.slice(8)||'—'}<small>{i.data.date?new Date(i.data.date+'T12:00:00').toLocaleString('en',{month:'short'}):'TBC'}</small></span><div><strong>{i.title}</strong><small>{i.data.round} · {i.data.time||'Time to confirm'}</small></div><ArrowUpRight size={13}/></button>)}{!upcoming.length&&<p className="panel-empty">No upcoming interviews. Your next conversation will appear here.</p>}</section>
 <section className="dashboard-panel"><div className="panel-heading"><h2>Follow-ups</h2><span>{followups.length} NEXT ACTIONS</span></div>{followups.slice(0,4).map(j=><button className="dashboard-row" key={j.id} onClick={()=>navigate('Applications')}><span className="small-check">○</span><div><strong>{j.data.next_action}</strong><small>{j.company} · {j.data.deadline||'No date set'}</small></div></button>)}{!followups.length&&<p className="panel-empty">A little follow-through goes a long way. Add your next action to an application.</p>}</section>
 <section className="dashboard-panel"><div className="panel-heading"><h2>Goals in motion</h2><button className="text-action" onClick={()=>navigate('Career Goals')}>View all</button></div>{goals.filter(g=>g.data.status==='Active').slice(0,3).map(g=><div className="dashboard-goal" key={g.id}><strong>{g.title}</strong><span>{goalProgress(g)}%</span><div className="prep-progress"><div style={{width:goalProgress(g)+'%'}}/></div></div>)}{!goals.length&&<button className="text-action" onClick={()=>navigate('Career Goals')}>Set your first career goal</button>}</section>
 <section className="dashboard-panel span-two"><div className="panel-heading"><h2>Resume performance</h2><span>OBSERVED OUTCOMES</span></div><table className="data-table"><thead><tr><th>Resume</th><th>Applications</th><th>Responses</th><th>Interviews</th></tr></thead><tbody>{analytics.resume_performance.slice(0,4).map(r=><tr key={r.id}><td>{r.name}</td><td>{r.applications}</td><td>{r.responses}</td><td>{r.interviews}</td></tr>)}</tbody></table><p className="form-note">Recorded outcomes, not a claim of causation.</p></section><section className="dashboard-panel"><div className="panel-heading"><h2>Recent activity</h2><span>YOUR WORKSPACE</span></div>{activity.slice(0,5).map(a=><div className="recent-row" key={a.id}><Check size={12}/><div>{a.action}<small>{new Date(a.created_at).toLocaleDateString()}</small></div></div>)}</section></div></>
}
